!------------------------------------------------------------------------
!      Density of volumic charge function (second member) 
!------------------------------------------------------------------------
 
double precision function f(x,y,nsd)

  use electros_2D,  only: DirBC_Func,NeuBC_Func

  implicit none
  double precision :: x,y
  integer          :: nsd

  f=0.d0
    
  if (trim(adjustl(DirBC_Func)) == 'User_Defined'.or. &
      trim(adjustl(NeuBC_Func)) == 'User_Defined') then
     
!    Volumic charge defined as a function by User
!    Please modify the code below in case you want to provide your own
!    function to compute Volumic charge

    f=0.d0
        
  elseif (trim(adjustl(DirBC_Func)) == 'Example_1'.or.&
          trim(adjustl(NeuBC_Func)) == 'Example_1') then
     
!    Second member function of Example 1 (point charge) 

    f=0.d0

  elseif (trim(adjustl(DirBC_Func)) == 'Example_2'.or.&
          trim(adjustl(NeuBC_Func)) == 'Example_2') then
     
!    Second member function of Example 2 (point charge) 

    f=0.d0

  elseif(trim(adjustl(DirBC_Func)) == 'Example_3'.or.&
         trim(adjustl(NeuBC_Func)) == 'Example_3') then

!    Sectond member function of Example 3 (volumic charge) 

    if (nsd.eq.2) then
      f = 1.e-10
    endif

  endif

  return
end

!------------------------------------------------------------------------
!      Exact solution function of the examples
!------------------------------------------------------------------------
 
double precision function fexac(x,y)

  use electros_2D,  only: DirBC_Func,NeuBC_Func

  implicit none
  double precision            :: x,y
  double precision            :: a,rint,rext
  double precision, parameter :: ql    = 1.e-10
  double precision, parameter :: epsi0 = 8.854e-12
  double precision, parameter :: pi    = dacos(-1.d0) 

!    Exact function example 1 (point source) 
!    potential generated by a charge at origin.

  if (trim(adjustl(DirBC_Func)) == 'Ejemplo_1'.or.&
      trim(adjustl(NeuBC_Func)) == 'Ejemplo_1') then
    if (dsqrt(x**2+y**2).ne.0.d0) then
      fexac = ql/(2*pi*epsi0)*dlog(1.d0/dsqrt(x**2+y**2))
    else
      fexac = 10.14679d0
    endif
  endif

!     Exact function example 2 	(line sources)
!     potential generated by a uniform distribution of charges at a circumference of radius a.

  if (trim(adjustl(DirBC_Func)) == 'Ejemplo_2'.or.&
      trim(adjustl(NeuBC_Func)) == 'Ejemplo_2') then
    a=0.5d0
    if (dsqrt(x**2+y**2).ge.a) then
      fexac = ql*a/epsi0 *dlog(1.d0/dsqrt(x**2+y**2))
    else
      fexac = ql*a/epsi0 *dlog(1.d0/a) !  3.9143
    endif
  endif

!     Exact function example 3 	(surface sources)
!     potential generated by a uniform distribution of charges in a circle of radius rint

  if (trim(adjustl(DirBC_Func)) == 'Ejemplo_3'.or.&
      trim(adjustl(NeuBC_Func)) == 'Ejemplo_3') then
    rint  = 0.5d0
    rext  = 2.d0
    if (dsqrt(x**2+y**2).le.rint) then
      fexac = ql*rint**2/(2.d0*epsi0)*(dlog(2.d0/rint)+0.5d0)& 
         - ql/(4*epsi0)*(x**2+y**2)
    else
      fexac = ql*rint**2/(2*epsi0) * dlog(2.d0/dsqrt(x**2+y**2))
    endif
  endif

  return
end
